[package]
name = "xdd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num="0.4"

[dev-dependencies]
clap={version="3.2",features = [ "derive" ]}